// Convex generated API - Stub for build
// Real version generated by `npm run convex`

export const api = {
  tasks: {
    listTasks: "tasks:listTasks" as any,
    createTask: "tasks:createTask" as any,
    updateTask: "tasks:updateTask" as any,
    deleteTask: "tasks:deleteTask" as any,
  },
  content: {
    listContent: "content:listContent" as any,
    createContent: "content:createContent" as any,
    updateContent: "content:updateContent" as any,
    addImage: "content:addImage" as any,
    deleteContent: "content:deleteContent" as any,
  },
  calendar: {
    listEvents: "calendar:listEvents" as any,
    createEvent: "calendar:createEvent" as any,
    updateEvent: "calendar:updateEvent" as any,
    deleteEvent: "calendar:deleteEvent" as any,
  },
  memories: {
    listMemories: "memories:listMemories" as any,
    createMemory: "memories:createMemory" as any,
    updateMemory: "memories:updateMemory" as any,
    deleteMemory: "memories:deleteMemory" as any,
  },
  team: {
    listTeamMembers: "team:listTeamMembers" as any,
    createTeamMember: "team:createTeamMember" as any,
    updateTeamMember: "team:updateTeamMember" as any,
    deleteTeamMember: "team:deleteTeamMember" as any,
    getOfficeStatus: "team:getOfficeStatus" as any,
    updateOfficeStatus: "team:updateOfficeStatus" as any,
  },
};
